### ISSUE TITLE
tsc finds recursive reference with TestConfigOverrides

### ISSUE THREAD

**Issue by DanielYang-AT** [javierbrea/cypress-fail-fast#151]
Does the `TestConfigOverrides` need to partial extend itself? I get a tsc recursive reference when checking with `npx tsc` with this package implemented. I tried removing `extends Partial<TestConfigOverrides>` in my local node_modules and it appears to have worked.

https://github.com/javierbrea/cypress-fail-fast/blob/b95ca06e8da9728980ba76277be463598334c43f/index.d.ts#L12

`error TS2310: Type 'TestConfigOverrides' recursively references itself as a base type`

**Comment by javierbrea** [comment]
Hi @DanielYang-AT,

Yes, you're right, this seems to be a problem, even when I don't understand why are you trying to compile your Cypress code using `tsc`, because Cypress does the `compilation` by itself. (take into account that I'm not a TypeScript expert, to be honest I haven't used it as much as I'd like). Note also that [`tsc` used through `npx` seems to be deprecated](https://www.npmjs.com/package/tsc), although this is probably not related to the problem.

The intention when extending the `TestConfigOverrides` interface was to keep the original Cypress tests configuration properties, but adding those supported by this plugin.

Please let me check if removing the extension will produce other undesired effects, for example stop supporting original Cypress options, which would be a great problem. Meanwhile, and only as a temporal workaround, maybe you could try to use `tsc` options for ignoring files, such as `--excludeFiles` or `--excludeDirectories`.

Thanks for notifying the problem 😃

**Comment by DanielYang-AT** [comment]
Thanks for the detailed feedback. I didn't notice that npx was running and old version of the compiler, the intent is to have typescript compile the project. You should be able to get the same with `./node_modules/.bin/tsc`.

The project I'm working in has typescript compile checks for all committed code. It's possible we should be skipping type checks for the Cypress project completely, I'll look into adding this package to the ignored files.

**Comment by javierbrea** [comment]
Hi again @DanielYang-AT,

Hi have created a Typescript project from the scratch, and I have added Cypress tests to it using also Typescript. I have confirmed that this is a problem if you run `tsc` on the Cypress folder, which might have sense in order to check types, even when it is not needed to run tests.
I have also confirmed that removing the `extends` works properly and both the plugin and Cypress options continue working properly, so I will merge it to the release branch and I will publish a new release after adding `tsc` compilation to the TypeScript E2E tests in order to check it always.

Thanks for your contribution! 😃
