### ISSUE TITLE
Upgrade to be compatible with Cypress 9.0.0

### ISSUE THREAD

**Issue by jeff00seattle** [javierbrea/cypress-fail-fast#169]
Cypress just release version 9.0.0.
https://docs.cypress.io/guides/references/changelog#9-0-0

cypress-fail-fast is not compatible:
https://github.com/javierbrea/cypress-fail-fast/blob/main/package.json#L44

**Comment by javierbrea** [comment]
Hi @jeff00seattle , thanks for the notice.
I'm sorry but I have detected some errors when running E2E tests with Cypress v9, so I have to investigate further in order to make the plugin compatible with the new version.

![Captura de pantalla 2021-11-11 a las 19 53 54](https://user-images.githubusercontent.com/983381/141353303-e74da9a7-8c73-4a8b-b64c-fc420faab07a.png)

**Comment by javierbrea** [comment]
Hi @jeff00seattle,
Cypress 9 is already supported in [release v3.3.0](https://github.com/javierbrea/cypress-fail-fast/releases/tag/v3.3.0) 😃

**Comment by jeff00seattle** [comment]
@javierbrea Thank you!
