### ISSUE TITLE
Instead of skipping the test case, can we fail the trailing tests for reporting purposes?

### ISSUE THREAD

**Issue by hansiemithun** [javierbrea/cypress-fail-fast#231]
**Is your feature request related to a problem? Please describe.**

The library is helping to skip the test cases. But the CI reporting will report the skipped test cases as untested and this gives the wrong presentation for the management and gives less confidence to take to release.

**Describe the solution you'd like**
Though skipping test cases is a wise solution, can we fail the trailing test cases, at least the report gets generated as tested and failed instead of untested?

**Describe alternatives you've considered**

**Additional context**
Add any other context or examples about the feature request here.

**Comment by javierbrea** [comment]
Hi @hansiemithun ,

Apart from the technical details implied on this request, in my honest opinion it would be confusing if the skipped tests are reported as failed. Because, in fact, they were no executed, so it is completely right to report them as "untested".

I think that it is completely normal that a skipped test gives less confidence to take the release, so I don't consider it as a wrong presentation.
