### ISSUE TITLE
Disable plugin local and enable on CI

### ISSUE THREAD

**Issue by aleksey-ilin** [javierbrea/cypress-fail-fast#242]
I want to disable cypress-fail-fast local but enable it on CI. I tried to use this config `Env: {FAIL_FAST_ENABLED: false,},`
and run tests with command `CYPRESS_FAIL_FAST_PLUGIN=true yarn cypress` for enable plugin on CI, but it is not working.
Is it another way?

**Comment by javierbrea** [comment]
Hi @aleksey-ilin , use `FAIL_FAST_ENABLED` to disable the fail fast globally when you pretend to enable it only in certain spec files using the [configuration by test](https://github.com/javierbrea/cypress-fail-fast#configuration-by-test). Or use `CYPRESS_FAIL_FAST_PLUGIN` to completely disable the plugin.

In any case, use the same method for enabling/disabling it. So, if you are using `FAIL_FAST_ENABLED=false` to disable it, you should use also `FAIL_FAST_ENABLED=true` to enable it.

In your case, you are setting `CYPRESS_FAIL_FAST_PLUGIN=true` in the environment (which, by the way, is already true by default), and `FAIL_FAST_ENABLED` continues being false, because you set it in your env file and you are not modifying it.

So, my recommendation is to use `FAIL_FAST_PLUGIN` instead of `FAIL_FAST_ENABLED`, and remember to use the same var both in your env file and command.
