### ISSUE TITLE
Custom Callback On Test Fail

### ISSUE THREAD

**Issue by alexlee-dev** [javierbrea/cypress-fail-fast#85]
**Is your feature request related to a problem? Please describe.**
I need to perform some specific "cleanup" logic when a test fails. Currently, if a test fails and I'm using this plugin, the other tests get skipped properly, but I need to perform cleanup logic prior to the test runner exiting.

**Describe the solution you'd like**
The usage would be:

_cypress/plugins/index.js_
```js
...
module.exports = (on, config) => {
  require('cypress-fail-fast/plugin')(on, config, { 
    cleanup: () => {
      // custom cleanup function
    }
  });
  return config;
};
...
```

The implementation would be

_cypress-fail-fast/src/plugin.js_
```js
...
[SHOULD_SKIP_TASK]: function (value) {
  if (value === true) {
    if (cleanup) {
      cleanup()
    }
    if (onCancelCallback) {
      onCancelCallback()
    }
  }
}
...
```

**Describe alternatives you've considered**
Using `parallelCallbacks`. However, since I'm not genuinely using parallel tests, the plugin sets `parallelCallbacks` to `false`, and the `if (onCancelCallback)` line never gets hit.

**Additional context**
N/A

**Comment by javierbrea** [comment]
Hi @alexlee-dev,

The callback that you are proposing is out of the scope of the plugin, in my opinion. I think that you should not use this plugin callbacks to perform any logic on failing tests apart of setting the parallel flag, which is its original purpose.

Maybe you can use one of the Cypress events in order to know when a test has failed, and then perform your cleanup logic. You could use the [Cypress `fail` event](https://docs.cypress.io/api/events/catalog-of-events#Catching-Test-Failures), for example.

Anyway, you could also use the `onCancel` callback of this plugin if you set the strategy to "parallel" (if you always return `false` in the `isCancelled` callback it will be like having the strategy set as "run" 😉  ). I think it would work, but it wouldn't be the best approach probably.

**Comment by javierbrea** [comment]
Any news on this @alexlee-dev? Was the answer useful?
If you don't have any more doubts about this question, I will close the issue.

**Comment by alexlee-dev** [comment]
@javierbrea Yes, i'm sorry for the delay. Your reply was helpful. Feel free to close. Thanks.
